SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

DROP TABLE IF EXISTS [Loan].[MsfoEventLog]

CREATE TABLE [Loan].[MsfoEventLog](
	[MsfoEventLogID] uniqueidentifier NOT NULL,
	[EventType] int NOT NULL,
	[ForDate] date NOT NULL,
	[Start] datetime NOT NULL,
	[ErrorCount] int NOT NULL
 CONSTRAINT [MsfoEventLogID] PRIMARY KEY CLUSTERED 
(
	[MsfoEventLogID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
